apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-upload
  template:
    metadata:
      labels:
        app: image-upload
    spec:
      containers:
      - image: bcesnik/rso-image-uploader:1.0.0-SNAPSHOT-10.1
        name: image-upload
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: gcloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://image-catalog-service:8083
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://35.205.56.107:5432/images_db
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: postgres
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: KUMULUZEE_DATASOURCES0_PASSWORD
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: image-upload
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: image-upload
