apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-update-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-update
  template:
    metadata:
      labels:
        app: image-update
    spec:
      containers:
      - image: bcesnik/rso-image-uploader:1.0.0-SNAPSHOT-6.1
        name: image-update
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: image-update
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: image-update
