kumuluzee:
  name: image-upload-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/ImageDS
      connection-url: jdbc:postgresql://35.205.56.107:5432/images_db
      username: postgres
      password: adminadmin
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/ImageDS
      etcd-health-check:
        connection-url: http://etcd:2379/health
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: comments-endpoint
        url-pattern: /v1/uploads/*
        status-codes: "200, 404, 500"

